-- 코드를 입력하세요
SELECT P.PRODUCT_ID,PRODUCT_NAME,SUM(AMOUNT)*PRICE TOTAL
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON P.PRODUCT_ID=O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL DESC, P.PRODUCT_ID