-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
) A
JOIN(
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
    FROM JULY
    GROUP BY FLAVOR
) B
ON(A.FLAVOR=B.FLAVOR)
ORDER BY A.TOTAL+B.TOTAL DESC
LIMIT 3;